### ISSUE TITLE
ProcessWire 3.0.32 to old for the module?

### ISSUE THREAD

**Issue by tbba** [uiii/ProcessWire-FieldtypePDF#10]
ERROR: Module is not installable because not all required dependencies are currently met. 

I run PW 3.0.3.2 - error says that version is to old for the module:

"Requires 	ProcessWire 3.0.32 < 3.0"  <-- ????

In case this is a PW bug I reported that also for PW already.

**Comment by uiii** [comment]
Did you use the `devns` branch? The master branch is only for PW 2.x. Look at the top of the README.

**Comment by uiii** [comment]
I will add this information to the summary in module's info (visible in the admin).

**Comment by tbba** [comment]
great. So users know whats going on before visiting the GitHub site.
The problem came when using the PW updater to do the updates. That one isn't aware of a dev version.

 Maybe it would be good to use different version numbering for the 2.x and the 3.x branch. 

"3.0.32 < 3.0" is still funny math :-)
