### ISSUE TITLE
Error when using a large (>2MB) pdf file

### ISSUE THREAD

**Issue by jmartsch** [uiii/ProcessWire-FieldtypePDF#13]
Hi @uiii if I try to upload the attached pdf mylarge.pdf, I get an error "Unable to create new image". The file itself seems to upload fine, but then when the image is generated (in backend), the error occurs.

Is there any way to prevent this? Maybe this has to do with memory limits?
Maybe we could use the resize option of imagemagick when the image is beeing created? How would one do that?
[mylarge.pdf](https://github.com/uiii/ProcessWire-FieldtypePDF/files/2090053/mylarge.pdf)

**Comment by uiii** [comment]
Hi, this looks like it's a problem with memory limit, try to increase it.

**Comment by jmartsch** [comment]
Hi, I solved the problem with setting the density to 72. Now it works fine with large DIN A1 PDFs.
