### ISSUE TITLE
Does not work in ProcessWire 3.x

### ISSUE THREAD

**Issue by gerritvanaaken** [uiii/ProcessWire-FieldtypePDF#9]
Version 1.0.1 and 1.1.0 both have massive problems. Is this module still under development? Would be great to use for future projects!

**Comment by uiii** [comment]
Hi, I apologize, it is difficult for me to find some time for development of this module. I haven't tried it with PW 3.x yet. Please be patient, or you can help me and investigate the problems.

**Comment by gerritvanaaken** [comment]
No apologize needed :-) I’l have a look into it, when I have some spare time.

**Comment by uiii** [comment]
I'm working on it now. The main problem are namespaces because PW 3.x compile only files which aren't in any namespace but I have some files with the namespace other than `\ProcessWire`. ryancramerdesign/ProcessWire#1987

**Comment by uiii** [comment]
ProcessWire 3.x compatible version is now on [devns](https://github.com/uiii/ProcessWire-FieldtypePDF/tree/devns) branch

**Comment by uiii** [comment]
ProcessWire 3.x compatible version is now on [devns](https://github.com/uiii/ProcessWire-FieldtypePDF/tree/devns) branch
